### ISSUE TITLE
Migrate leaflet to mapbox-gl

### ISSUE THREAD

**Issue by milovanderlinden** [Code-for-All/lockdown#46]
To get support from mapbox, because of the smaller footprint and because of the use of webGL, we want to migrate leaflet to mapbox

**Comment by davojta** [comment]
I plan to work on it next days during the hackathon

**Comment by davojta** [comment]
Draft plan
* [ ] run mapbox map inside preact instead of leaflet
  * [ ] correct import all resources into preact component
  * [ ] init the map within correct container
  * [ ] draw basic info
* [ ] replicate territory click and info popup
* [ ] current position 
* [ ] highlight feature on cover

**Comment by LarsDenBakker** [comment]
Let's move to mapbox when there is an objective benefit. We do use the mapbox tiles right now.

Leaflet is 40kb (https://bundlephobia.com/result?p=leaflet@1.6.0) while mapbox is 184kb (https://bundlephobia.com/result?p=mapbox-gl@1.9.1) so it's going to significantly increase the initial load of the application. Is there a reason to switch? Are we missing any features? 

There has been some contact with the mapbox team, so perhaps we can check if they are able to provider a lighter build as well.

**Comment by davojta** [comment]
@LarsDenBakker I just started on the project and don't know all the technical reasons behind decisions and all restrictions which the project has. 

From my naive user perspective, the mapbox gl js will bring the following benefits over leaflet
1) the map is working without visual artifacts - leaflet is really rendered only visible/viewport part of the map
2) the UX of the map is better on mapbox - it is working smoothly without feeling that the project is broken (right now it is a lug between different layers
3) mapbox gl js is using vector tiles which is better for network consumption and browser cache utilization and it gives the ability to use fractional zooms without  pixelization
4) leaflet is generally is more low level and quite outdated (based mostly on the old "tile" concept of the client maps).

Personally I will prefer to work as a dev with mapbox as more dev friendly lib and move to leaflet if I need more granular and low-level control over map control workflow (and if I need tiles for satellite imagery for example)

PS I'm biased because I'm mapbox employee but I have working experience both with leaflet (develop quite a complex browser turn-base strategy with a leaflet on frontend) and mapbox gl js (transferring also quite complex react app from static map image base solution to dynamic WebGL solution)

**Comment by davojta** [comment]
@LarsDenBakker I'm looking around and find the ticket - https://github.com/mapbox/mapbox-gl-js/issues/6320 . Seems the mapbox-gl-js cant be smaller then ~180kb due to webgl nature (it needs to render all map stuff on the client). 

So it is a real trade-off between vector tiles vs raster tiles.

**Comment by davojta** [comment]
Some rough numbers 
- raster tile to look in Europe 
start of the app
![image](https://user-images.githubusercontent.com/893650/80250228-108d8c00-867c-11ea-89f2-9e84abeae00f.png)
zoom-in to territories and pan a little bit
![image](https://user-images.githubusercontent.com/893650/80250310-3d41a380-867c-11ea-8c5f-4020111a34a8.png)
Result: +1.6m for looking / zooming /  the map

Vector tile on the local machine
Load the app
![image](https://user-images.githubusercontent.com/893650/80250435-885bb680-867c-11ea-8811-c2e0c88cba03.png)

Zoom and look at the map on the same territory
![image](https://user-images.githubusercontent.com/893650/80250727-120b8400-867d-11ea-86ae-d1e412bfe5c9.png)

Result: +1.4m for looking / zooming /  the map

It still needs to test the full functionality (but builds on netlify + full-featured), but the difference is here - trade-off initial load to UX and robust later usage of the map.

**Comment by davojta** [comment]
I'm based my first step from the code in that PR - https://github.com/Code-for-All/lockdown/pull/47 . There is also the previous discussion about leaflet vs mapbox-gl-js

**Comment by LarsDenBakker** [comment]
I appreciate that you're digging into this, nice analysis!

So you're saying after the initial map is loaded, it's a lot smoother to move around and load parts of the map? That's definitely an interesting metric to consider.

I think the goal for this app is to work well on phones, and to serve the global market. We therefore really need to take low-end mobile phones and bad networks into considerations. These are much slower than what most devs are used to considering. 

Based on the recommendations by google: https://web.dev/performance-budgets-101/#establish-a-baseline we have a budget of about 170kb for the initial load, mapbox already exceeds that. I can't begin to imagine all the features and functionalities that go into this, and I'm certain that there are opportunities there to build in only the necessary functionalities or lazy load things on demand.

That being said, we could explore extracting mapbox to a separate chunk or loading it from a CDN and enable long term caching. We could do some comparisons side by side and let the numbers speak for themselves.

**Comment by davojta** [comment]
The testing on the Netlify deployment
Load the app
<img width="925" alt="image" src="https://user-images.githubusercontent.com/893650/80258089-1179ea00-868b-11ea-85a4-1d4b68667ca7.png">

Zoom and look around
<img width="925" alt="image" src="https://user-images.githubusercontent.com/893650/80258187-471ed300-868b-11ea-91ae-91faa253092c.png">

Results: +1.4 Mb for using the map

**Comment by davojta** [comment]
Load app with optimized styles for mapbox-gl-js
<img width="925" alt="image" src="https://user-images.githubusercontent.com/893650/80259037-5868df00-868d-11ea-9460-a1ddfbede961.png">

After zooming and looking on the map
<img width="925" alt="image" src="https://user-images.githubusercontent.com/893650/80259137-8ea65e80-868d-11ea-82fe-4748e41683f6.png">

Results: +0.7mb for using the map

**Comment by davojta** [comment]
Here are the results from webpagetest for Jakarta

Leaflet
<img width="1267" alt="image" src="https://user-images.githubusercontent.com/893650/80261532-56a21a00-8693-11ea-9d8e-a86d8f5fc0b3.png">

Mapbox gl js
<img width="1267" alt="image" src="https://user-images.githubusercontent.com/893650/80261555-6a4d8080-8693-11ea-997b-b2d870f9db9b.png">

**Comment by davojta** [comment]
released
