### ISSUE TITLE
[backend] improve speed

### ISSUE THREAD

**Issue by LarsDenBakker** [Code-for-All/lockdown#80]
Right now the script takes quite a while to fully execute. Is there something we can do here to improve speed? Perhaps reducing the total amount of connection to the spreadsheet, or reducing the amount of data fetched.

**Comment by ilyasfoo** [comment]
Yes it seems the [batchGet](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.values/batchGet) API can help to reduce roundtrips by batching out for multiple worksheets.

The issue is our current library is yet to support it, but I think the changes needed to support is minimal.
