### ISSUE TITLE
[backend] reduce api calls to google to avoid rate limiting

### ISSUE THREAD

**Issue by thepassle** [Code-for-All/lockdown#81]
Currently the script does separate calls to the google sheets api to get the data for each separate country, we should optimize this to avoid getting rate limited

**Comment by ilyasfoo** [comment]
Yes it seems the [batchGet](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.values/batchGet) API can help to reduce roundtrips by batching out for multiple worksheets.

The issue is our current [library](https://github.com/theoephraim/node-google-spreadsheet) is yet to support it, but I think the changes needed to support is minimal.
